title: Shujaat Mirza
logo: /assets/img/headshot.jpeg
description: AI Safety Researcher at Microsoft | PhD in Computer Science from NYU 
show_downloads: false
google_analytics:
exclude: [vendor]
theme: jekyll-theme-minimal
